export const canvas = document.getElementById('canvas')
export const ctx = canvas.getContext('2d')
export const fileUpload = document.getElementById('fileUpload')
export const rangeContainer = document.getElementById('range-container')
export const moveSelector = document.getElementById('move-selector')
